"""Update user example model

Revision ID: 153036be3eed
Revises: 852ec83c6bbb
Create Date: 2020-11-19 08:23:17.421485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '153036be3eed'
down_revision = '852ec83c6bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_example', 'word', ['word'], ['word'])
    op.drop_column('user_example', 'original')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_example', sa.Column('original', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'user_example', type_='foreignkey')
    # ### end Alembic commands ###
