"""Change foreign key for user examples to word not word.id

Revision ID: 35ac5bde0c79
Revises: 153036be3eed
Create Date: 2020-11-19 08:42:01.560291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ac5bde0c79'
down_revision = '153036be3eed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('definition', sa.Column('word', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_definition_word'), 'definition', ['word'], unique=False)
    op.drop_constraint(None, 'definition', type_='foreignkey')
    op.create_foreign_key(None, 'definition', 'word', ['word'], ['word'])
    op.drop_column('definition', 'word_id')
    op.add_column('dictionary_example', sa.Column('word', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_dictionary_example_word'), 'dictionary_example', ['word'], unique=False)
    op.create_foreign_key(None, 'dictionary_example', 'word', ['word'], ['word'])
    op.create_index(op.f('ix_user_example_word'), 'user_example', ['word'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_example_word'), table_name='user_example')
    op.drop_constraint(None, 'dictionary_example', type_='foreignkey')
    op.drop_index(op.f('ix_dictionary_example_word'), table_name='dictionary_example')
    op.drop_column('dictionary_example', 'word')
    op.add_column('definition', sa.Column('word_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'definition', type_='foreignkey')
    op.create_foreign_key(None, 'definition', 'word', ['word_id'], ['id'])
    op.drop_index(op.f('ix_definition_word'), table_name='definition')
    op.drop_column('definition', 'word')
    # ### end Alembic commands ###
