"""Update word id col in example and definition models

Revision ID: 4a375b1ce819
Revises: 3f43a66799b4
Create Date: 2020-11-13 09:45:15.319251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a375b1ce819'
down_revision = '3f43a66799b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'definition', 'word', ['word_id'], ['id'])
    op.drop_column('definition', 'word')
    op.add_column('dictionary_example', sa.Column('word_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dictionary_example', 'word', ['word_id'], ['id'])
    op.drop_column('dictionary_example', 'word')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dictionary_example', sa.Column('word', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'dictionary_example', type_='foreignkey')
    op.drop_column('dictionary_example', 'word_id')
    op.add_column('definition', sa.Column('word', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'definition', type_='foreignkey')
    # ### end Alembic commands ###
