"""Add word ID to user example model

Revision ID: 4cef04cff360
Revises: 8f59063547bf
Create Date: 2020-11-17 09:30:04.125277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cef04cff360'
down_revision = '8f59063547bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_example', sa.Column('word_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_example', 'word', ['word_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_example', type_='foreignkey')
    op.drop_column('user_example', 'word_id')
    # ### end Alembic commands ###
