"""Add Polish and French to Bulk Translate model

Revision ID: 705364586aa9
Revises: fff9703069b8
Create Date: 2020-11-27 08:53:18.971620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '705364586aa9'
down_revision = 'fff9703069b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bulk_translate', sa.Column('french', sa.String(length=128), nullable=True))
    op.add_column('bulk_translate', sa.Column('polish', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bulk_translate', 'polish')
    op.drop_column('bulk_translate', 'french')
    # ### end Alembic commands ###
