"""Update user example model

Revision ID: 852ec83c6bbb
Revises: 4cef04cff360
Create Date: 2020-11-17 09:39:52.430589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852ec83c6bbb'
down_revision = '4cef04cff360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_example', 'original')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_example', sa.Column('original', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
