"""in use col added to accents model

Revision ID: 8f59063547bf
Revises: 32c977fdaeff
Create Date: 2020-11-16 11:06:48.921024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f59063547bf'
down_revision = '32c977fdaeff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('international_accent', sa.Column('in_use', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('international_accent', 'in_use')
    # ### end Alembic commands ###
