"""Remove UserTranslation model

Revision ID: 98b604f896cf
Revises: 421cfd301061
Create Date: 2020-11-06 10:14:44.550816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b604f896cf'
down_revision = '421cfd301061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_translation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_translation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('source_language', sa.VARCHAR(length=2), nullable=True),
    sa.Column('destination_language', sa.VARCHAR(length=2), nullable=True),
    sa.Column('input', sa.TEXT(), nullable=True),
    sa.Column('output', sa.TEXT(), nullable=True),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.Column('last_modified', sa.DATETIME(), nullable=True),
    sa.Column('attempt', sa.INTEGER(), nullable=True),
    sa.Column('success', sa.INTEGER(), nullable=True),
    sa.Column('fail', sa.INTEGER(), nullable=True),
    sa.Column('level', sa.INTEGER(), nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), nullable=True),
    sa.Column('ignored', sa.BOOLEAN(), nullable=True),
    sa.Column('starred', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('deleted IN (0, 1)'),
    sa.CheckConstraint('ignored IN (0, 1)'),
    sa.CheckConstraint('starred IN (0, 1)'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
