"""Add attempts field and last_modified filed to User example model

Revision ID: a7c25f392658
Revises: 225aec1ec184
Create Date: 2020-09-24 17:36:03.874671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c25f392658'
down_revision = '225aec1ec184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_example', sa.Column('attempt', sa.Integer(), nullable=True))
    op.add_column('user_example', sa.Column('last_modified', sa.DateTime(), nullable=True))
    op.drop_column('user_example', 'skip')
    op.add_column('user_translation', sa.Column('attempt', sa.Integer(), nullable=True))
    op.add_column('user_translation', sa.Column('last_modified', sa.DateTime(), nullable=True))
    op.drop_column('user_translation', 'skip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_translation', sa.Column('skip', sa.INTEGER(), nullable=True))
    op.drop_column('user_translation', 'last_modified')
    op.drop_column('user_translation', 'attempt')
    op.add_column('user_example', sa.Column('skip', sa.INTEGER(), nullable=True))
    op.drop_column('user_example', 'last_modified')
    op.drop_column('user_example', 'attempt')
    # ### end Alembic commands ###
