"""Add lt and el

Revision ID: be2d2be29631
Revises: 35ac5bde0c79
Create Date: 2020-11-19 11:17:49.286657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be2d2be29631'
down_revision = '35ac5bde0c79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bulk_translate', sa.Column('greek', sa.String(length=128), nullable=True))
    op.add_column('bulk_translate', sa.Column('latin', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bulk_translate', 'latin')
    op.drop_column('bulk_translate', 'greek')
    # ### end Alembic commands ###
