"""Create Example and Definition tables

Revision ID: f32614c561a8
Revises: 
Create Date: 2020-08-26 08:48:09.386810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f32614c561a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=64), nullable=True),
    sa.Column('etymology', sa.Text(), nullable=True),
    sa.Column('pronunciation', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_word'), 'words', ['word'], unique=True)
    op.create_table('definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=64), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['word'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sentences', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'sentences', 'words', ['word'], ['id'])
    op.drop_column('sentences', 'created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentences', sa.Column('created', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'sentences', type_='foreignkey')
    op.drop_column('sentences', 'timestamp')
    op.drop_table('definitions')
    op.drop_index(op.f('ix_words_word'), table_name='words')
    op.drop_table('words')
    # ### end Alembic commands ###
