"""Add default value to user lang prefs

Revision ID: fff9703069b8
Revises: c0b598ba2aa9
Create Date: 2020-11-26 07:09:27.742185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff9703069b8'
down_revision = 'c0b598ba2aa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_language_preference', sa.Column('french', sa.Boolean(), nullable=True))
    op.add_column('user_language_preference', sa.Column('polish', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_language_preference', 'polish')
    op.drop_column('user_language_preference', 'french')
    # ### end Alembic commands ###
